name: Node CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ðŸ“¦ Install dependencies
        run: npm install

      - name: ðŸš€ Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            echo "=== WHOAMI ==="
            whoami

            echo "=== HOME ==="
            echo $HOME

            echo "=== LIST HOME ==="
            ls -la ~

            echo "=== GO TO PROJECT ==="
            cd ~/ci-cd-node

            echo "=== GIT STATUS ==="
            git status

            echo "=== PULL LATEST CODE ==="
            git pull origin main

            echo "=== INSTALL PACKAGES ==="
            npm install

            echo "=== PM2 STATUS BEFORE ==="
            pm2 list || true

            echo "=== START OR RELOAD APP ==="
            pm2 reload ecosystem.config.js --update-env || pm2 start ecosystem.config.js

            pm2 save

            echo "=== PM2 STATUS AFTER ==="
            pm2 list